# Generated by Django 4.0.1 on 2022-02-06 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agende', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='unidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_unid', models.CharField(max_length=65)),
                ('nome_unid', models.CharField(max_length=65)),
            ],
        ),
    ]
