# Generated by Django 4.0.1 on 2022-02-06 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agende', '0002_unidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cpf',
            field=models.CharField(default=None, max_length=65),
        ),
        migrations.AddField(
            model_name='usuario',
            name='data_nasc',
            field=models.DateField(default=None, max_length=11),
        ),
        migrations.AddField(
            model_name='usuario',
            name='senha',
            field=models.CharField(default=None, max_length=12),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nome',
            field=models.CharField(default=None, max_length=65),
        ),
    ]
