# Generated by Django 4.0.1 on 2022-02-06 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agende', '0003_usuario_cpf_usuario_data_nasc_usuario_senha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cpf',
            field=models.IntegerField(default=None, max_length=65),
        ),
    ]
