# Generated by Django 4.0.1 on 2022-02-06 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agende', '0004_alter_usuario_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidade',
            name='cod_unid',
            field=models.CharField(default=None, max_length=65),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='nome_unid',
            field=models.CharField(default=None, max_length=65),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='data_nasc',
            field=models.DateField(default=None),
        ),
        migrations.CreateModel(
            name='agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('cod_und', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agende.unidade')),
                ('cpf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agende.usuario')),
            ],
        ),
    ]
